spring:
  application:
    name: employee-svc
  profiles:
    active: dev
  devtools:
    livereload:
      enabled: true
      port: 35749
  config:
    import: optional:configserver:http://localhost:8888/config-svc/
server:
  servlet:
    context-path: /employee-svc
  port: ${PORT:8081}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}


