spring:
  application:
    name: discovery-svc

server:
  port: ${PORT:8761}
  servlet:
    context-path: /discovery-svc


# initialize eureka server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-Zone: ${DEFAULT_ZONE:http://localhost:8761}