spring:
  application:
    name: gateway-svc
  main:
    web-application-type: reactive

server:
  port: ${PORT:8080}
  servlet:
    context-path: /gateway-svc
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}

