spring:
  application:
    name: config-svc
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mrwin95/config-file-server.git
          password: '{cipher}30c0af3b592add14310b3d99e558439b80242eb00a3e3d62266a30e740c26351ad8a18cbcfcc22609688f15c8f157ad9c529784d2ddfc116ce9bd9c4b283b103'
          username: '{cipher}fd5d6fd4118e8425aaad6da0c745b0c583c647a49f8450c62239a8469a5ebd28'
          default-label: main
      enabled: false

server:
  servlet:
    context-path: /config-svc
  port: 8888
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
encrypt:
  key: Thang
