spring:
  application:
    name: config-svc
  profiles:
    active: dev
  datasource:
    username: postgres
    password: Thang123
    url: jdbc:postgresql://localhost:5432/microapp
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform:
  #    database-platform: org.postgresql.Driver

  cloud:
    config:
      server:
        git:
          uri: https://github.com/mrwin95/config-file-server.git
          password: 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
          username: mrwin95
          default-label: main
server:
  servlet:
    context-path: /config-svc
  port: 8888
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
