spring:
  application:
    name: department-svc

server:
  servlet:
    context-path: /department-svc
  port: ${PORT:8082}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}